//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities1 : DbContext
    {
        public Entities1()
            : base("name=Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Table_Chemicals_Delivery> Table_Chemicals_Delivery { get; set; }
        public virtual DbSet<Table_Contact_Persons> Table_Contact_Persons { get; set; }
        public virtual DbSet<Table_Delivery> Table_Delivery { get; set; }
        public virtual DbSet<Table_Gender> Table_Gender { get; set; }
        public virtual DbSet<Table_Household_Chemicals> Table_Household_Chemicals { get; set; }
        public virtual DbSet<Table_Household_Delivery> Table_Household_Delivery { get; set; }
        public virtual DbSet<Table_Household_Goods> Table_Household_Goods { get; set; }
        public virtual DbSet<Table_Manufacturer> Table_Manufacturer { get; set; }
        public virtual DbSet<Table_Product_Stock> Table_Product_Stock { get; set; }
        public virtual DbSet<Table_Purpose_Chemistry> Table_Purpose_Chemistry { get; set; }
        public virtual DbSet<Table_Role> Table_Role { get; set; }
        public virtual DbSet<Table_Sale_Chemicals> Table_Sale_Chemicals { get; set; }
        public virtual DbSet<Table_Sale_Houshould> Table_Sale_Houshould { get; set; }
        public virtual DbSet<Table_Sales> Table_Sales { get; set; }
        public virtual DbSet<Table_Staff> Table_Staff { get; set; }
        public virtual DbSet<Table_Suppliers> Table_Suppliers { get; set; }
    }
}
