//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Sales
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_Sales()
        {
            this.Table_Sale_Chemicals = new HashSet<Table_Sale_Chemicals>();
            this.Table_Sale_Houshould = new HashSet<Table_Sale_Houshould>();
        }
    
        public int id_sales { get; set; }
        public int staff_code { get; set; }
        public System.DateTime date_sales { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Sale_Chemicals> Table_Sale_Chemicals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Sale_Houshould> Table_Sale_Houshould { get; set; }
        public virtual Table_Staff Table_Staff { get; set; }
    }
}
