//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Staff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_Staff()
        {
            this.Table_Sales = new HashSet<Table_Sales>();
        }
    
        public int id_staff { get; set; }
        public string surname { get; set; }
        public string name { get; set; }
        public string patronymic { get; set; }
        public int role { get; set; }
        public System.DateTime date_birth { get; set; }
        public byte[] employee_photo { get; set; }
        public int gender { get; set; }
        public string login { get; set; }
        public int password { get; set; }
    
        public virtual Table_Gender Table_Gender { get; set; }
        public virtual Table_Role Table_Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Sales> Table_Sales { get; set; }
    }
}
