//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Delivery
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_Delivery()
        {
            this.Table_Chemicals_Delivery = new HashSet<Table_Chemicals_Delivery>();
            this.Table_Household_Delivery = new HashSet<Table_Household_Delivery>();
        }
    
        public int id_delivery { get; set; }
        public int provider_code { get; set; }
        public System.DateTime delivery_date { get; set; }
        public int employee_code { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Chemicals_Delivery> Table_Chemicals_Delivery { get; set; }
        public virtual Table_Staff Table_Staff { get; set; }
        public virtual Table_Suppliers Table_Suppliers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Household_Delivery> Table_Household_Delivery { get; set; }
    }
}
