//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Household_Chemicals
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_Household_Chemicals()
        {
            this.Table_Chemicals_Delivery = new HashSet<Table_Chemicals_Delivery>();
            this.Table_Product_Stock = new HashSet<Table_Product_Stock>();
            this.Table_Sale_Chemicals = new HashSet<Table_Sale_Chemicals>();
        }
    
        public int id_chemicals { get; set; }
        public string name { get; set; }
        public int manufacturer_code { get; set; }
        public int destination_code { get; set; }
        public double cost { get; set; }
        public byte[] photo_chemicals { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Chemicals_Delivery> Table_Chemicals_Delivery { get; set; }
        public virtual Table_Manufacturer Table_Manufacturer { get; set; }
        public virtual Table_Purpose_Chemistry Table_Purpose_Chemistry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Product_Stock> Table_Product_Stock { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Sale_Chemicals> Table_Sale_Chemicals { get; set; }
    }
}
