//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Sale_Chemicals
    {
        public int id_sale_inform { get; set; }
        public int sales_code { get; set; }
        public int product_code { get; set; }
        public int quantity { get; set; }
    
        public virtual Table_Household_Chemicals Table_Household_Chemicals { get; set; }
        public virtual Table_Sales Table_Sales { get; set; }
    }
}
