//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Product_Stock
    {
        public int id_product_in_stock { get; set; }
        public Nullable<int> product_code { get; set; }
        public int quantity { get; set; }
        public Nullable<int> chemical_code { get; set; }
    
        public virtual Table_Household_Chemicals Table_Household_Chemicals { get; set; }
        public virtual Table_Household_Goods Table_Household_Goods { get; set; }
    }
}
