//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Household_Goods
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_Household_Goods()
        {
            this.Table_Household_Delivery = new HashSet<Table_Household_Delivery>();
            this.Table_Product_Stock = new HashSet<Table_Product_Stock>();
            this.Table_Sale_Houshould = new HashSet<Table_Sale_Houshould>();
        }
    
        public int id_household_goods { get; set; }
        public string name { get; set; }
        public int manufacturer_code { get; set; }
        public double cost { get; set; }
        public string photo_household { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Household_Delivery> Table_Household_Delivery { get; set; }
        public virtual Table_Manufacturer Table_Manufacturer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Product_Stock> Table_Product_Stock { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Sale_Houshould> Table_Sale_Houshould { get; set; }
    }
}
