//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Manufacturer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_Manufacturer()
        {
            this.Table_Household_Chemicals = new HashSet<Table_Household_Chemicals>();
            this.Table_Household_Goods = new HashSet<Table_Household_Goods>();
        }
    
        public int id_manufacturer { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public int code_contact_person { get; set; }
    
        public virtual Table_Contact_Persons Table_Contact_Persons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Household_Chemicals> Table_Household_Chemicals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Household_Goods> Table_Household_Goods { get; set; }
    }
}
